---
- name: OpenPBS Installation
  hosts: pbs
  become: true
  vars:
    pbs_version: 22.05.11
  tasks:
    - name: Update hostname
      ansible.builtin.hostname:
        name: "{{ pbs_hostname }}"

    - name: Ensure /etc/hosts file is updated
      ansible.builtin.template:
        src: etc/hosts.j2
        dest: /etc/hosts
        mode: "0644"

    - name: Ensure dnf-plugins-core is installed in order to hwloc-devel and libedit-devel packages
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present

    - name: Dependencies installed
      ansible.builtin.dnf:
        state: present
        name:
          - gcc
          - make
          - rpm-build
          - libtool
          - hwloc-devel
          - libX11-devel
          - libXt-devel
          - libedit-devel
          - libical-devel
          - ncurses-devel
          - perl
          - postgresql-devel
          - postgresql-contrib
          - python3-devel
          - tcl-devel
          - tk-devel
          - expat-devel
          - openssl-devel
          - libXext
          - libXft
          - autoconf
          - automake
          - gcc-c++

    - name: Ensure swig rpm package file downloaded
      ansible.builtin.get_url:
        url: https://repo.almalinux.org/almalinux/8/AppStream/x86_64/os/Packages/swig-4.0.2-3.module_el8.4.0%2B2100%2B4bdcb5c6.x86_64.rpm
        dest: /tmp/swig.rpm
        mode: "0644"

    - name: Ensure swig rpm package installed
      ansible.builtin.yum:
        name: /tmp/swig.rpm
        state: present
        disable_gpg_check: true

    - name: Ensure OpenPBS prerequirements packages are installed
      ansible.builtin.dnf:
        state: present
        name:
          - expat
          - libedit
          - postgresql-server
          - postgresql-contrib
          - python3
          - sendmail
          - sudo
          - tcl
          - tk
          - libical

    - name: Ensure OpenPBS tar file downloaded
      ansible.builtin.get_url:
        url: https://github.com/openpbs/openpbs/archive/refs/tags/v{{ pbs_version }}.tar.gz
        dest: /root/openpbs.tar.gz
        mode: "0644"
      register: download_openpbs_tar

    - name: Ensure OpenPBS tar file extracted
      ansible.builtin.unarchive:
        src: /root/openpbs.tar.gz
        dest: /root
        remote_src: true
      when: download_openpbs_tar.changed

    - name: Build OpenPBS
      ansible.builtin.shell: |
        ./autogen.sh \
        && ./configure --prefix=/opt/openpbs \
        && make -j2 && make install
      args:
        chdir: /root/openpbs-{{ pbs_version }}
      ignore_errors: true
      when: download_openpbs_tar.changed

    - name: Post-install OpenPBS
      ansible.builtin.shell: /opt/openpbs/libexec/pbs_postinstall
      when: download_openpbs_tar.changed

    - name: Ensure pbs_iff and pbs_rcp permissions are set
      ansible.builtin.file:
        path: /opt/openpbs/sbin/{{ item }}
        mode: "4755"
      with_items:
        - pbs_iff
        - pbs_rcp

    - name: Ensure /etc/pbs.conf file is created
      ansible.builtin.template:
        src: pbs.conf.j2
        dest: /etc/pbs.conf
        mode: "0644"
      notify:
        - Restart OpenPBS

    - name: Ensure ports are opened
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - 15001/tcp # All communication to server
        - 15002/tcp # All communication to MoM
        - 15007/tcp # PBS information storage and retrieval
        # - 6200/tcp # All communication to license server
        - 17001/tcp # All communication to pbs_comm

  handlers:
    - name: Restart OpenPBS
      ansible.builtin.service:
        name: pbs
        state: restarted
