roles:
  - name: cloudalchemy.node_exporter
    version: 2.0.0
  - name: cloudalchemy.grafana
    version: 0.18.0
  # Because of unknown issue, we cannot use `ansible-galaxy install`.
  - name: cloudalchemy.prometheus
    src: git+https://github.com/flat35hd99/ansible-prometheus.git
    version: master