---
- name: Playbook for prerequirements
  ansible.builtin.import_playbook: prerequirements.yaml

- name: Playbook for OpenPBS
  ansible.builtin.import_playbook: pbs.yaml
  vars:
    pbs_server_name: pbs-server # This value should be the same as pbs_hostname of pbs_master in inventory.yaml

- name: Playbook for User
  ansible.builtin.import_playbook: user.yaml

- name: Playbook for Monitoring
  ansible.builtin.import_playbook: monitoring.yaml
