---
- name: Playbook for prerequirements
  ansible.builtin.import_playbook: prerequirements.yaml

- name: Playbook for OpenPBS
  ansible.builtin.import_playbook: pbs.yaml

- name: Playbook for Monitoring
  ansible.builtin.import_playbook: monitoring.yaml
