- hosts: localhost
  gather_facts: no
  become: yes
  vars:
    cobbler_server_ip: "192.168.122.207"
  tasks:
    - name: Install utility
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - tar
        - git
    
    - name: Enable EPEL
      yum:
        name: epel-release
        state: present
      
    - name: Install Cobbler
      yum:
        name: "{{ item }}"
        state: present
        enablerepo: "epel"
      with_items:
        - cobbler

    - name: Write Cobbler settings.yaml
      template:
        src: settings.yaml.j2
        dest: /etc/cobbler/settings.yaml
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart cobblerd

    - name: Enable Cobbler
      service:
        name: cobblerd
        state: started
        enabled: yes

  handlers:
    - name: Restart cobblerd
      service:
        name: cobblerd
        state: restarted
