name: Build Kickstart Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: ["linux", "windows", "darwin"]
        goarch: ["amd64", "arm64"]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version-file: kickstart-server/go.mod
          check-latest: true
          cache: true
          cache-dependency-path: kickstart-server/go.sum

      - name: Build Kickstart Server
        run: go build -o kickstart-server .
        working-directory: kickstart-server
        env:
          GIN_MODE: "release"
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}

      - name: Upload Kickstart Server
        uses: actions/upload-artifact@v3
        with:
          name: kickstart-server-${{ matrix.goos }}-${{ matrix.goarch }}
          path: kickstart-server/kickstart-server
