name: Build Kickstart Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.4"

      - name: Build Kickstart Server
        run: go build -o kickstart-server .
        working-directory: kickstart-server
        env:
          GIN_MODE: "release"

      - name: Upload Kickstart Server
        uses: actions/upload-artifact@v2
        with:
          name: kickstart-server
          path: kickstart-server/kickstart-server
